### ISSUE TITLE
Rendering problem on iOS 10

### ISSUE THREAD

**Issue by junedomingo** [kirankalyan5/react-native-segmented-control-tab#10]
![56cc3012-5c8e-4e33-b589-7cd4f0009e73](https://cloud.githubusercontent.com/assets/5106887/23650172/2a66bfa8-035c-11e7-8471-06efd28c36c6.JPG)

Here you can see some shadow effect in the inactive tab. 
this happens in actual device

**Comment by kirankalyan5** [comment]
@junedomingo can you share the code for the above ? It's working fine for me.

**Comment by junedomingo** [comment]
Custom styles are inlined for now.
```
<SegmentedControlTab
	tabStyle={{ 
        backgroundColor: 'white', 
        marginTop: Platform.OS === 'ios' ? 15 : 10, 
        borderColor: '#163258', 
        marginBottom: 10 
    }}
	tabTextStyle={{ color: '#163258' }}
	activeTabStyle={{ backgroundColor: '#163258' }}
	values={['Schedules', 'Tasks']}
	selectedIndex={this.state.segmentedControlTabIndex}
	onTabPress={index => { this._filterSchedules(index); }}
/>
```

**Comment by junedomingo** [comment]
@kirankalyan5, This is already in `release` build by the way, my  iOS version is `10.2`.
No problem in Simulator.

**Comment by whan** [comment]
I guess this is React Native bug on iOS, even this simple piece of codes will have the same issue:

<TouchableOpacity >
        <View style={{
          width: 100, borderBottomLeftRadius: 5, borderTopLeftRadius: 5, borderColor: 'blue',
          paddingHorizontal: 10,
          paddingVertical: 5,
          borderWidth: 1,
        }}>
          <Text style={{ width: 30 }}>text</Text>
        </View>
      </TouchableOpacity>

**Comment by whan** [comment]
`<TouchableOpacity >
        <View style={{
          width: 100, borderBottomLeftRadius: 5, borderTopLeftRadius: 5, borderColor: 'blue',
          paddingHorizontal: 10,
          paddingVertical: 5,
          borderWidth: 1,
        }}>
          <Text style={{ width: 30 }}>text</Text>
        </View>
      </TouchableOpacity>`

**Comment by asessa** [comment]
This glitch is visible only when your side border radius is greater than 0 and you have an element on its side with borders.

I've disabled the left/right border and works for me (iOS 10.2.1 device).

Try to disable the border left/right width on L51/52:

```
        const firstTabStyle = index === 0 ? [{ borderRightWidth: 0, borderTopLeftRadius: borderRadius, borderBottomLeftRadius: borderRadius }] : {}
        const lastTabStyle = index === values.length - 1 ? [{ borderLeftWidth: 0, borderTopRightRadius: borderRadius, borderBottomRightRadius: borderRadius }] : {}
```

@kirankalyan5  if it's ok for you I can submit a PR.

**Comment by bedemiralp** [comment]
This appears to be a bug with React Native itself. Many people have reported similar issues:
- https://github.com/facebook/react-native/issues/8577
- https://github.com/facebook/react-native/issues/11897
- https://github.com/facebook/react-native/issues/10823
- https://github.com/facebook/react-native/issues/4604

**Comment by kirankalyan5** [comment]
@here - I have published the latest version, have a look!

**Comment by asessa** [comment]
@kirankalyan5 I've tested with the latest version and the problem is still there

**Comment by giautm** [comment]
I still got that problem after upgrade to Expo's SDK 18.

**Comment by bcitdaltond** [comment]
Still have this problem too

Example:
![image](https://user-images.githubusercontent.com/23248970/28085560-ed6d16dc-6630-11e7-960e-3595a0b96721.png)

```
    let tank = 60 //can be higher or smaller

    rightTank: {
        borderTopLeftRadius: 40,
        borderBottomLeftRadius: 40,
        borderColor: 'black',
        borderTopWidth: 3,
        borderLeftWidth: 3,
        borderBottomWidth: 3,
        height: 120,
        width: window.width/tank - 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    middleTank: {
        borderColor: 'black',
        borderTopWidth: 3,
        borderBottomWidth: 3,
        borderLeftWidth: 3,
        height: 120,
        width: window.width/tank - 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    leftTank: {
        borderTopRightRadius: 40,
        borderBottomRightRadius: 40,
        borderColor: 'black',
        borderWidth: 3,
        height: 120,
        width: window.width/tank - 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
```

**Comment by kirankalyan5** [comment]
Hi Guys, I have fixed this issue, I have published the latest version have a look.
Attaching the screen shot for reference.
![img_9281](https://user-images.githubusercontent.com/13114538/28488773-3f8bf176-6ecf-11e7-92b1-b8bc23a1a3d7.PNG)
![img_9282](https://user-images.githubusercontent.com/13114538/28488774-3fd26d04-6ecf-11e7-93fb-76ee9194b2d2.PNG)

**Comment by kennykswan** [comment]
Note with this fix, if there are only two tabs, there is no border between them.

**Comment by kirankalyan5** [comment]
@kennykswan I agree, but when it's two tabs I don't find a need of border between them.
PFA
![image](https://user-images.githubusercontent.com/13114538/29201152-644a6402-7e79-11e7-8a3b-9ae7a987e634.png)

**Comment by jamesholcomb** [comment]
I tried the fix.  With three tabs on Simulator, seeing some extra spacing between second and third tab when third tab is selected.

RN 0.46.4
iOS 10.3
 
![image](https://user-images.githubusercontent.com/362729/29620605-06d81c46-87e4-11e7-8b26-b630275325f8.png)

**Comment by jamesholcomb** [comment]
This resolved it for me:

```javascript
tabStyle={[
  tabStyle,
  index !== 0 && index !== values.length - 1
    ? { marginLeft: Platform.OS === "ios" ? -1 : 0 }
    : {}
]}

**Comment by MassieurHunter** [comment]
hello guys, the last commit produce the same issue for ios 9 and 10 when there's only 2 tabs

**Comment by luigiquero** [comment]
I got rid of the artefact in by using Math.round in borderRadius provided directly to SegmentedControlTab.
Apparently it doesn't like floats

**Comment by radiospiritsapp** [comment]
still getting this issue in ios 6s device with 2 tabs.

**Comment by hsparihar-systango** [comment]
still getting this issue in ios 6s device with 2 tabs.

**Comment by GavinThomas1192** [comment]
I'm also still getting this issue on ios 6s
